# Generated by Django 3.2.9 on 2021-11-29 16:31

import core.models.article_img_path
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('article_title', models.CharField(max_length=300)),
                ('is_publish', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'article',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ArticleImgPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('path', models.ImageField(upload_to=core.models.article_img_path.image_directory_path)),
                ('created_by', models.ForeignKey(db_column='created_by', db_constraint=False, default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='articleimgpath_create_related', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(db_column='deleted_by', db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='articleimgpath_delete_related', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(db_column='updated_by', db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='articleimgpath_update_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'article_img_path',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='author',
            name='acc_bank',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='author_related', to='core.accbank'),
        ),
        migrations.CreateModel(
            name='ArticleParagraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('order', models.IntegerField(default=0)),
                ('content', models.TextField(blank=True, null=True)),
                ('is_supporter_view_only', models.BooleanField(default=False)),
                ('article', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='paragraphs', to='core.article')),
                ('article_img_path', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='articleparagraph_related', to='core.articleimgpath')),
                ('created_by', models.ForeignKey(db_column='created_by', db_constraint=False, default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='articleparagraph_create_related', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(db_column='deleted_by', db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='articleparagraph_delete_related', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(db_column='updated_by', db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='articleparagraph_update_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'article_paragraph',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='articles', to='core.author'),
        ),
        migrations.AddField(
            model_name='article',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', db_constraint=False, default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='article_create_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='deleted_by',
            field=models.ForeignKey(db_column='deleted_by', db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='article_delete_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='updated_by',
            field=models.ForeignKey(db_column='updated_by', db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='article_update_related', to=settings.AUTH_USER_MODEL),
        ),
    ]
