# Generated by Django 3.2.9 on 2021-12-15 15:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_authorwithdraw_flow_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorwithdraw',
            name='withdraw_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
