# Generated by Django 3.2.9 on 2021-12-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_authorwithdraw_withdraw_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='publish_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='articleparagraph',
            name='paragraph_title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
