# Generated by Django 3.2.9 on 2021-12-20 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20211218_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleparagraph',
            name='article_img',
        ),
        migrations.RemoveField(
            model_name='articleparagraph',
            name='paragraph_title',
        ),
        migrations.RemoveField(
            model_name='articleparagraph',
            name='type',
        ),
    ]
